### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by Rem0o** [wiiznokes/LibreFanControl#91]
Hi,

I'm the author of [FanControl](https://github.com/Rem0o/FanControl.Releases). 

Cool project. I got no issue with the project itself, I think you got very good inspirations 😉. 
Only thing, please use "Libre Fan Control" in the naming everywhere in the program, or whatever other name you like really, just to be consistent with this repo name, and to avoid conflict with the "original" [Fan Control](https://getfancontrol.com/). 

Thank you and good luck on the project.

**Comment by wiiznokes** [comment]
Hi, thank you for your message. 
Sorry for my messages on your Github issues, it's just that I had been there before creating the project. 
I have no problem by renaming in LibreFanControl, will do it in next release.

Good luck in your project too 😉.
